# This script compares use of
# openxlsx, writexl and arrow libraries for saving data
# The results show that arrow is the faster library
# We read the parquet files generated by RFLDA.R and use them as test data
#


library(openxlsx)
library(writexl)
library(arrow, warn.conflicts = FALSE)

source("common_functions.R")

test_result_file_name <- "../optimisation_data/parquet_and_excel_write_result.csv"

input_folder <- "../output_data/"

optimisation_folder <- "../optimisation_data/"

test_file_names <- c(
  "FeatureScore.parquet",
  "lncRNA-disease-ALL.parquet",
  "lncRNA-disease-associations-2697.parquet",
  "lncRNA-disease-Excl0.parquet",
  "lncRNA-disease-Excl0-regulation.parquet",
  "NegativeSample.parquet",
  "PositiveSample.parquet",
  "TrainingSample-gaccuracy.parquet",
  "TrainingSample.parquet",
  "UnlabeledSample.parquet",
  "UnlabeledSampleScore-300-features.parquet"
)

full_test_file_names <- unlist(lapply(test_file_names, function(x) paste(input_folder, x, sep = "")))


dfs <- sapply(full_test_file_names, ReadParquetData)
nrows <- unlist(sapply(dfs, nrow, USE.NAMES = FALSE))
ncols <- unlist(sapply(dfs, ncol, USE.NAMES = FALSE))
dfsize <- unlist(sapply(dfs, object.size, USE.NAMES = FALSE))

openxlsx_times <- sapply(dfs, WriteAndTimeOpenXLSX, USE.NAMES = FALSE)
writexl_times <- sapply(dfs, WriteAndTimeWriteXL, USE.NAMES = FALSE)
arrow_times <- sapply(dfs, WriteAndTimeArrow, USE.NAMES = FALSE)

test_result_df <- data.frame(
  test_file_names,
  writexl_times,
  openxlsx_times,
  arrow_times,
  nrows,
  ncols,
  dfsize
)

colnames(test_result_df) <- c(
  "file_name",
  "writexl_duration_s",
  "openxlsx_duration_s",
  "arrow_duration_s",
  "nrows",
  "ncols",
  "dfsize_b"
)

# sort data frame by size
test_result_df <- test_result_df[order(test_result_df$dfsize_b), ]

write.csv(test_result_df, test_result_file_name, row.names = FALSE)
